server:
  port: 5003

spring:
  application:
    name: account-service
  cloud:
    alibaba:
      seata:
        enabled: true # 1.0新特性，需要依赖seata-spring-boot-starter 默认为true
        enable-auto-data-source-proxy: true  # 牵扯到回滚
        tx-service-group: my_test_tx_group  # 需要与config.txt中的 service.vgroupMapping.seata_test_group=default保持一致
        server:
          vgroup-mapping:
            my_test_tx_group: default # 需要与config.txt中的 service.vgroupMapping.seata_test_group=default 保持一致
          #grouplist:
          #  default: 127.0.0.1:8091
          disable-global-transaction: false
        registry:  ## 注册中心
          type: nacos #注册nacos
          nacos:
            application: seata-server  #nacos中seata-server启动注册成功后的服务名称
            server-addr: 127.0.0.1:8848
            username: nacos
            password: nacos
        config: ## 配置中心  与register.conf文件中的保持一致
          type: nacos
          nacos:
            server-addr: 127.0.0.1:8848
            group: SEATA_GROUP  #与register.conf文件中的保持一致
            username: nacos
            password: nacos
            namespace: public
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://1.15.114.247:3306/seata_account
    username: root
    password: 123456

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml


